# Copyright (c) Akos Polster. All rights reserved.
#
# References:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -scheme ShopDemo -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
- pod lib lint --allow-warnings
